### ISSUE TITLE
Support template variables for application name

### ISSUE THREAD

**Issue by yeya24** [pyroscope-io/grafana-datasource-plugin#1]
With the pull mode support in pyroscope, it would be great to support template variables for the datasource plugin so that I can use prometheus to discover pods in k8s and use template variables to get the apps dynamicly.

**Comment by Rperry2174** [comment]
Thanks @yeya24 ! Your expertise and feedback is _very_  helpful! 

I definitely agree.. we don't have this on the main roadmap because of the different repos, but we have made a lot of improvements to Pyroscope since we last updated the datasource / panel plugins (i.e. Tags, Pull Mode, diff view, etc.) and we've had a couple requests to bring our Grafana integrations up to speed.

I think your idea would be a great follow-up once we merge the pull mode PR! We'll look more into it and see how we can prioritize it
