### ISSUE TITLE
Can't find Endpoint field

### ISSUE THREAD

**Issue by linuxwind** [pyroscope-io/grafana-datasource-plugin#17]
We install 1.2.0 pyroscope grafana daatasource plugin， but can't find Endpoint field.

We have only Pyroscope instance and API Key  field.
![WX20230316-104256@2x](https://user-images.githubusercontent.com/1060929/225497005-b5799ce0-4c5e-4bc0-a2ed-3d2bb4473d00.png)

plz fix it. Thanks.

**Comment by eh-am** [comment]
Hi, I don't understand your problem. You can use the `Pyroscope instance` field to tell where pyroscope lives.

If you want to set an specific endpoint (like a path), that's not currently possible, since we call multiple endpoints (`/api/apps`, `/api/render` etc). But we will be happy to reevaluate the implementation if you provide a more concrete use case.
